### ISSUE TITLE
执行 npm run dev 报错

### ISSUE THREAD

**Issue by logyoo** [artiely/vue-admin-artiely#1]
![_20170823111409](https://user-images.githubusercontent.com/16537800/29597318-6cf92956-87f4-11e7-8232-e110dad9cbdb.png)

**Comment by artiely** [comment]
文件漏传了，重新拉取就ok了

**Comment by daiyanze** [comment]
`npm run dev`的时候报错了
```
This dependency was not found:

* @/components/views/Icon in ./src/router/menu.js
```
不好意思，Icon这个文件在pages里面，估计你手误不小心弄错了。

**Comment by artiely** [comment]
@daiyanze 不好意思由于Icon与业务没有关系被移到了pages目录下，下午会有新功能 ，到时候一并更新
